### PR TITLE
Exclude models and templates from code coverage

### PR DESCRIPTION
**Pull request by pl9ed**
Forgot to include sonar.exclusions property in the previous commit.

### CODE REVIEW

**Review by IkenoXamos — CHANGES_REQUESTED** [review]
This PR includes a commit that belongs to a different PR, leading to many unrelated changes.

**Comment by pl9ed** [comment]
@IkenoXamos Is there a way to merge the sonarcloud addition into https://github.com/Docutest-1/docutest-back/commit/3c8ea1dad8fb752f463adf6cf5092035aebeb301 without also including 240e03a in this branch? Or will we just have to rebase in master?

**Comment by IkenoXamos** [comment]
> @IkenoXamos Is there a way to merge the sonarcloud addition into [3c8ea1d](https://github.com/Docutest-1/docutest-back/commit/3c8ea1dad8fb752f463adf6cf5092035aebeb301) without also including [240e03a](https://github.com/Docutest-1/docutest-back/commit/240e03a679a2be50b7583910540b90c3f5a6a601) in this branch? Or will we just have to rebase in master?

This should be doable without affecting master at all. The reason it is shown here as a separate commit is because the commit hash changed compared to master. I would start by performing `git pull --rebase origin master` to make sure this has all of the same commits. This will end up with a duplicate commit so to speak. The commit message will say the same thing, but the hashcodes will be different. The one in this branch, [`240e03a`](https://github.com/Docutest-1/docutest-back/commit/240e03a679a2be50b7583910540b90c3f5a6a601), can likely be just removed with an interactive rebase, barring any extra modifications that you wanted to be part of this PR.

In general, it is rather difficult to rebase master while it is actively being worked on, since any rebasing will change the commit hashcodes. This then makes it difficult to update any branches to have the same changes, because Git doesn't realize the old commits should be removed. All it knows is that the hashcodes are different. Rebasing master usually would only occur when there are few to no other branches.

Ah, I think I understand now how this situation arose. Most likely you rebased and changed the original commits that had already been merged into master.

If we want, I could directly go in and remove the old commit from master before merging this PR in. You would still have to unmodify the [`240e03a`](https://github.com/Docutest-1/docutest-back/commit/240e03a679a2be50b7583910540b90c3f5a6a601) commit, because it does need to match the same hashcode that is on the master branch.

**Comment by pl9ed** [comment]
Ok, I've removed the unnecessary commits. From the temp models I added earlier, it seems like Sonar is excluding models/templates correctly now.

**Review by IkenoXamos — APPROVED** [review]
Looks good

**Pull request merged**
